# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.24
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 17.0
org_name: IT Brasil
org_slug: itbrasil-odoo
rebel_module_groups: []
repo_description: Improvements to Odoo's Brazilian localization by IT Brasil
repo_name: Improvements to Odoo's Brazilian localization
repo_slug: itbr-l10n-brazil
repo_website: https://github.com/itbrasil-odoo/itbr-l10n-brazil
use_pyproject_toml: true
use_ruff: false

